# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\settings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings_Dialog(object):
    def setupUi(self, Settings_Dialog):
        Settings_Dialog.setObjectName("Settings_Dialog")
        Settings_Dialog.resize(478, 253)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images-src/tools.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings_Dialog.setWindowIcon(icon)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Settings_Dialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_inputType_2 = QtWidgets.QLabel(Settings_Dialog)
        self.label_inputType_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_inputType_2.setObjectName("label_inputType_2")
        self.verticalLayout_5.addWidget(self.label_inputType_2)
        self.comboBox_inputDevice = QtWidgets.QComboBox(Settings_Dialog)
        self.comboBox_inputDevice.setObjectName("comboBox_inputDevice")
        self.verticalLayout_5.addWidget(self.comboBox_inputDevice)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_inputType = QtWidgets.QLabel(Settings_Dialog)
        self.label_inputType.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_inputType.setObjectName("label_inputType")
        self.verticalLayout_3.addWidget(self.label_inputType)
        self.radioButton_single = QtWidgets.QRadioButton(Settings_Dialog)
        self.radioButton_single.setChecked(True)
        self.radioButton_single.setObjectName("radioButton_single")
        self.inputTypeButtonGroup = QtWidgets.QButtonGroup(Settings_Dialog)
        self.inputTypeButtonGroup.setObjectName("inputTypeButtonGroup")
        self.inputTypeButtonGroup.addButton(self.radioButton_single)
        self.verticalLayout_3.addWidget(self.radioButton_single)
        self.radioButton_double = QtWidgets.QRadioButton(Settings_Dialog)
        self.radioButton_double.setObjectName("radioButton_double")
        self.inputTypeButtonGroup.addButton(self.radioButton_double)
        self.verticalLayout_3.addWidget(self.radioButton_double)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_first = QtWidgets.QGroupBox(Settings_Dialog)
        self.groupBox_first.setObjectName("groupBox_first")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_first)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_firstChannel = QtWidgets.QComboBox(self.groupBox_first)
        self.comboBox_firstChannel.setObjectName("comboBox_firstChannel")
        self.verticalLayout.addWidget(self.comboBox_firstChannel)
        self.verticalLayout_4.addWidget(self.groupBox_first)
        self.groupBox_second = QtWidgets.QGroupBox(Settings_Dialog)
        self.groupBox_second.setEnabled(False)
        self.groupBox_second.setObjectName("groupBox_second")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_second)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_secondChannel = QtWidgets.QComboBox(self.groupBox_second)
        self.comboBox_secondChannel.setObjectName("comboBox_secondChannel")
        self.verticalLayout_2.addWidget(self.comboBox_secondChannel)
        self.verticalLayout_4.addWidget(self.groupBox_second)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBoxEnableFilter = QtWidgets.QCheckBox(Settings_Dialog)
        self.checkBoxEnableFilter.setObjectName("checkBoxEnableFilter")
        self.verticalLayout_6.addWidget(self.checkBoxEnableFilter)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(Settings_Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_energy = QtWidgets.QLineEdit(Settings_Dialog)
        self.lineEdit_energy.setObjectName("lineEdit_energy")
        self.horizontalLayout_4.addWidget(self.lineEdit_energy)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(Settings_Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit_zcr = QtWidgets.QLineEdit(Settings_Dialog)
        self.lineEdit_zcr.setObjectName("lineEdit_zcr")
        self.horizontalLayout_5.addWidget(self.lineEdit_zcr)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(Settings_Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lineEdit_entropy = QtWidgets.QLineEdit(Settings_Dialog)
        self.lineEdit_entropy.setObjectName("lineEdit_entropy")
        self.horizontalLayout_6.addWidget(self.lineEdit_entropy)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(Settings_Dialog)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(Settings_Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.button_selectFile = QtWidgets.QPushButton(Settings_Dialog)
        self.button_selectFile.setObjectName("button_selectFile")
        self.horizontalLayout_2.addWidget(self.button_selectFile)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Settings_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Settings_Dialog)

    def retranslateUi(self, Settings_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Settings_Dialog.setWindowTitle(_translate("Settings_Dialog", "Settings"))
        self.label_inputType_2.setText(_translate("Settings_Dialog", "Select the input device :"))
        self.label_inputType.setText(_translate("Settings_Dialog", "Select the type of input :"))
        self.radioButton_single.setText(_translate("Settings_Dialog", "Single channel"))
        self.radioButton_double.setText(_translate("Settings_Dialog", "Two channels"))
        self.groupBox_first.setTitle(_translate("Settings_Dialog", "First channel"))
        self.groupBox_second.setTitle(_translate("Settings_Dialog", "Second channel"))
        self.checkBoxEnableFilter.setText(_translate("Settings_Dialog", "Enable Filter"))
        self.label_2.setText(_translate("Settings_Dialog", "Max Energy : "))
        self.label_3.setText(_translate("Settings_Dialog", "Max ZCR :"))
        self.label_4.setText(_translate("Settings_Dialog", "Max Entropy :"))
        self.label.setText(_translate("Settings_Dialog", "Select the output file or folder :"))
        self.button_selectFile.setText(_translate("Settings_Dialog", "..."))

from . import analyzer_rc
